version: '2'

services:
  vault:
    build:
      context: vault-enterprise
      args:
        IMAGE: ${VAULT_IMAGE}
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=vault:8200
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_LICENSE=${VAULT_LICENSE}
    volumes:
      - ./data:/data
  rundeck:
    hostname: rundeck
    build:
      context: rundeck
      args:
        IMAGE: ${RUNDECK_IMAGE}
    mem_limit: ${mem_limit}
    #command: -Dlogging.config=/home/rundeck/server/config/logback.groovy
    environment:
    - RUNDECK_EXEC_CMD=script/configure.sh
    - RUNDECK_GRAILS_URL=http://localhost:4442
    - RUNDECK_DATABASE_DRIVER=org.mariadb.jdbc.Driver
    - RUNDECK_DATABASE_USERNAME=rundeck
    - RUNDECK_DATABASE_PASSWORD=rundeck
    - RUNDECK_DATABASE_URL=jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false
    - RUNDECK_STORAGE_PROVIDER_1_TYPE=vault-storage
    - RUNDECK_STORAGE_PROVIDER_1_PATH=keys
    - RUNDECK_STORAGE_PROVIDER_1_REMOVEPATHPREFIX=true
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_SECRETBACKEND=secret
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_PREFIX=app
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_ADDRESS=http://vault:8200
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_BEHAVIOUR=vault
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_ENGINEVERSION=2
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_MAXRETRIES=10
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_RETRYINTERVAL=10
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_OPENTIMEOUT=30
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_READTIMEOUT=30
    # auth approle
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_AUTHBACKEND=approle
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_AUTHNAMESPACE=rundeck
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_APPROLEID=${VAULT_APPROLE_ID}
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_APPROLESECRETID=${VAULT_APPROLE_SECRET_ID}
    - RUNDECK_STORAGE_PROVIDER_1_CONFIG_NAMESPACE=rundeck/demo
    ports:
    - "4442:4440"
    volumes:
      - ./data/:/home/rundeck/vault-envs/
  mysql:
    image: mysql:5.7
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
